language: node_js
node_js:
  - "stable"
  - "7"
  - "6"
cache: yarn
install:
  - yarn
  - npm run bootstrap
  - yarn global add codecov
script:
  - npm run lint
  - npm run typecheck
  - npm run testonly -- --coverage && codecov
