language: node_js
node_js:
  - "stable"
  - "7"
  - "6"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4
  - yarn --version
install:
  - yarn
  - npm run bootstrap
  - yarn global add codecov
script:
  - npm run lint
  - npm run typecheck
  - npm run testonly -- --coverage && codecov
