environment:
  matrix:
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - choco install yarn
  - yarn --version
  - yarn install

cache:
  - node_modules
  - "%LOCALAPPDATA%\\Yarn"

test_script:
  - npm run lint -- --color
  - npm run typecheck
  - npm run testonly -- --coverage --colors

# Don't actually build.
build: off
